name: music_minds
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bot_toast: ^4.0.4
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.3.2
  logger: ^2.0.2+1
  dio: ^5.2.0+1
  shared_preferences: ^2.1.2
  intl: ^0.19.0
  image_picker: ^0.8.4+3
  flutter_screenutil: ^5.6.0
  go_router: ^14.3.0


  percent_indicator: ^4.2.3

  pin_code_fields: any
  flutter_localizations:
    sdk: flutter
    version: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
#  change_app_package_name: ^1.5.0
#  flutter_app_name: ^0.1.1



#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/pngs/launcher_icon.png"
#  min_sdk_android: 21

#flutter_app_name:
#  name: "Music Minds"
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/svgs/
    - assets/images/pngs/
    - assets/images/jpgs/
    - assets/json/
    - assets/user_profile.json
    - assets/musicians.json
    - assets/services.json
    - assets/bookings.json

  fonts:
    - family: Campton
      fonts:
        - asset: assets/fonts/campton/CamptonBlack.otf
        - asset: assets/fonts/campton/CamptonBlackItalic.otf
        - asset: assets/fonts/campton/CamptonBold.otf
        - asset: assets/fonts/campton/CamptonBoldItalic.otf
        - asset: assets/fonts/campton/CamptonBook.otf
        - asset: assets/fonts/campton/CamptonBookItalic.otf
        - asset: assets/fonts/campton/CamptonLight.otf
        - asset: assets/fonts/campton/CamptonLightItalic.otf
        - asset: assets/fonts/campton/CamptonMedium.otf
        - asset: assets/fonts/campton/CamptonMediumItalic.otf
        - asset: assets/fonts/campton/CamptonSemiBold.otf
        - asset: assets/fonts/campton/CamptonSemiBoldItalic.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
